import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    // flex: 1,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  title: {
    color: '#6379F4',
    fontFamily: 'NunitoSans-Bold',
    fontSize: 26,
    fontWeight: '600',
    marginTop: 60,
  },
  content: {
    flex: 2,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 18,
    marginTop: 30,
  },
  textLogin: {
    textAlign: 'center',
    color: '#3A3D42',
    fontSize: 24,
    fontFamily: 'NunitoSans-Bold',
    fontWeight: '600',
    marginTop: 40,
  },
  descLogin: {
    color: '#3A3D42',
    opacity: 0.6,
    textAlign: 'center',
    fontFamily: 'NunitoSans-Regular',
    fontSize: 16,
    marginTop: 20,
  },
  wrapperInput: {
    flexDirection: 'row',
    marginTop: 30,
    borderBottomWidth: 1,
    borderBottomColor: '#A9A9A9',
    width: '100%',
  },
  icon: {
    color: '#A9A9A9',
    opacity: 0.4,
    marginTop: 12,
    marginRight: 16,
  },
  textInput: {
    fontFamily: 'NunitoSans-Regular',
    width: '100%',
    color: '#6379F4',
    fontSize: 16,
  },
  wrapperError: {
    alignItems: 'center',
    marginTop: 10,
  },
  textError: {
    color: '#FF5B37',
    fontFamily: 'NunitoSans-SemiBold',
    fontSize: 16,
  },
  forgotPass: {
    marginTop: 15,
    textAlign: 'right',
    fontFamily: 'NunitoSans-SemiBold',
    color: '#3A3D42',
    opacity: 0.8,
  },
  wrapperButton: {
    marginTop: 260,
  },
  wrapperButtonReset: {
    marginTop: 270,
  },
  button: {
    backgroundColor: '#DADADA',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    padding: 13,
    bottom: 70,
  },
  buttonActive: {
    backgroundColor: '#6379F4',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    padding: 13,
    bottom: 70,
  },
  buttonText: {
    color: '#88888F',
    fontWeight: '600',
    fontSize: 18,
    fontFamily: 'NunitoSans-SemiBold',
  },
  buttonTextActive: {
    color: 'white',
    fontWeight: '600',
    fontSize: 18,
    fontFamily: 'NunitoSans-SemiBold',
  },
  wrapperInputOtp: {
    flexDirection: 'row',
    marginTop: 30,
    justifyContent: 'space-between',
  },
  textInputOtp: {
    borderRadius: 12,
    width: 47,
    height: 58,
    borderColor: 'grey',
    textAlign: 'center',
    borderWidth: 1,
    fontSize: 24,
    fontFamily: 'NunitoSans-Bold',
  },
  pinContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 50,
    marginBottom: 15,
  },
  numPadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 15,
    alignItems: 'center',
  },
  numPadNumber: {fontSize: 30, textAlign: 'center'},
  numPadPressable: {flex: 1},
  continueButton: {
    width: 'auto',
    backgroundColor: '#6379F4',
    height: 57,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transferBtnText: {
    color: 'white',
    fontSize: 18,
  },
  transferBtnTextDisabled: {
    color: '#88888F',
    fontSize: 18,
  },
  continueButtonDisabled: {
    width: 'auto',
    backgroundColor: '#DADADA',
    height: 57,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinBox: {
    width: 47,
    height: 58,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#A9A9A9',
    borderRadius: 10,
    fontSize: 40,
    padding: 0,
    textAlign: 'center',
  },
});
